name: Fetch Information
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }} # Use the PAT stored as a secret
    
    - name: Fetch JSON Data
      id: fetchdata
      run: |
        curl -o data/warStatus.json https://api.live.prod.thehelldiversgame.com/api/WarSeason/801/Status -H "Accept-Language: en-US,en;q=0.5"
        curl -o data/warInfo.json https://api.live.prod.thehelldiversgame.com/api/WarSeason/801/warinfo -H "Accept-Language: en-US,en;q=0.5"
    
    - name: Commit and Push if Changed
      run: |
        git config --global user.email "sector-hq@temp.com"
        git config --global user.name "sector-api-fetch"
        git add data/warStatus.json
        git add data/warInfo.json
        git commit -m "Update War Status JSON data" || echo "No changes to commit"
        git push
